Fix Cypress Test Flakiness by Executing cy.visit Before cy.request (#1537) (#1538)
This PR addresses intermittent failures in the AD Cypress tests related to a known issue in Cypress (https://github.com/cypress-io/cypress/issues/25397). The specific failure observed was:

```
Sample detector
"before all" hook for "Empty message with modal":
AssertionError: Timed out retrying after 60000ms: Expected to find element: `[data-test-subj="viewSampleDetectorLink"]`, but never found it.
```

To mitigate this issue, we applied a workaround suggested in the GitHub issue, ensuring that cy.visit is executed before cy.request. This change helps stabilize the tests by properly loading AD overview page  before making any API requests.

Testing:
* Ran all Cypress tests with the modified code to verify the fix.

Signed-off-by: Kaituo Li <kaituo@amazon.com>
(cherry picked from commit 221231d976d1c111e79827f0a8e29eacb64efd7b)

Co-authored-by: Kaituo Li <kaituo@amazon.com>